# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('MBCbigP_rcpp_hello_world', PACKAGE = 'MBCbigP')
}

test_add <- function(a, b) {
    .Call('MBCbigP_test_add', PACKAGE = 'MBCbigP', a, b)
}

